name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Construir imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: alex81974/mi-app-docker:latest
